services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: pets_db
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: clave_app
    ports:
      - "3308:3306"
    volumes:
      - ./sql/sql_mysql.sql:/docker-entrypoint-initdb.d/sql_mysql.sql
  api:
    build: .
    container_name: pets-api
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
  frontend:
    build: frontend
    container_name: pets-frontend
    environment:
      API_URL: http://api:8080/pet/list
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/var/www/html