services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: pets_db
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: clave_app
    ports:
      - "3308:3306"
    volumes:
      - ./sql/sql_mysql.sql:/docker-entrypoint-initdb.d/sql_mysql.sql